name: Test and Deploy via FTP
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node JS LTS
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install npm dependencies
      run: npm install

    - name: Build project
      run: npm run build -s

    - name: Run default tests
      run: npm run test -s

    - name: Upload files to website
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: "ftp.mkv25.net"
        user: ${{ secrets.FTP_SYNC_USERNAME }}
        password: ${{ secrets.FTP_SYNC_PASSWORD }}
        localDir: "build"