name: Lint and test PR
on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node JS LTS
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Use Playwright
      uses: microsoft/playwright-github-action@v1

    - name: Install npm dependencies
      run: npm install

    - name: Build project
      run: npm run build -s

    - name: Run default tests
      run: npm run test -s

    - name: Run integration tests
      run: npm run test:integration -s