name: Lint and test PR
on: 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node JS LTS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm install

    - name: Build project
      run: npm run build -s

    - name: Report contents of build folder
      run: ls build/xdfmadev/parcel

    - name: Run headless tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        working-directory: ./ #optional
        run: npm run test -s